# Generated by Django 5.1.7 on 2025-04-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0003_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="bio",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
