# Generated by Django 5.1.7 on 2025-04-03 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_alter_myuser_bio"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="bio",
            field=models.CharField(max_length=500),
        ),
    ]
