# Generated by Django 5.1.7 on 2025-04-05 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0005_alter_myuser_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
