# Generated by Django 5.1.7 on 2025-04-05 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0006_post_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="role",
            field=models.CharField(
                choices=[("USER", "User"), ("ADMIN", "Admin")],
                default="USER",
                max_length=10,
            ),
        ),
    ]
