# Generated by Django 5.1.7 on 2025-04-05 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0007_myuser_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="muted",
            field=models.BooleanField(default=False),
        ),
    ]
