# Generated by Django 5.1.7 on 2025-04-06 01:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0009_report"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reporter",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="filed_reports",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
