# Generated by Django 5.1.7 on 2025-04-06 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0010_report_reporter"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("HARRASSMENT", "Harassment"),
                    ("FRAUD", "Fraud"),
                    ("SPAM", "Spam"),
                    ("INAPPROPRIATE", "Inappropriate"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=15,
            ),
        ),
    ]
