# Generated by Django 5.1.7 on 2025-04-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0011_report_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="report",
            name="resolved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.CharField(
                choices=[
                    ("HARASSMENT", "Harassment"),
                    ("FRAUD", "Fraud"),
                    ("SPAM", "Spam"),
                    ("INAPPROPRIATE", "Inappropriate"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=15,
            ),
        ),
    ]
