# Generated by Django 5.1.7 on 2025-04-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0012_report_resolved_alter_report_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="myuser",
            name="bio",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
