# Generated by Django 5.1.7 on 2025-04-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0014_myuser_id_alter_myuser_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="myuser",
            name="id",
        ),
        migrations.AlterField(
            model_name="myuser",
            name="username",
            field=models.CharField(
                max_length=50, primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
