# Generated by Django 5.1.7 on 2025-04-06 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0015_remove_myuser_id_alter_myuser_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="myuser",
            name="banned",
            field=models.BooleanField(default=False),
        ),
    ]
