# Generated by Django 5.1.7 on 2025-04-07 00:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0016_myuser_banned"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("DELETE_USER", "Deleted User"),
                            ("MUTE_USER", "Muted User"),
                            ("UNMUTE_USER", "Unmuted User"),
                            ("BAN_USER", "Banned User"),
                            ("UNBAN_USER", "Unbanned User"),
                            ("DELETE_POST", "Deleted Post"),
                            ("ARCHIVE_POST", "Archived Post"),
                            ("UNARCHIVE_POST", "Unarchived Post"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("details", models.TextField(blank=True, max_length=500)),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="base.post",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="targeted_by_admin",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
