# Generated by Django 5.1.7 on 2025-04-07 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0017_adminlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("DELETE_USER", "Deleted User"),
                    ("TOGGLE_MUTED", "Toggled Muted"),
                    ("TOGGLE_BANNED", "Toggled Banned"),
                    ("DELETE_POST", "Deleted Post"),
                    ("TOGGLE_ARCHIVED", "Toggled Archived"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=20,
            ),
        ),
    ]
